from fpdf import FPDF
import os

class PMS_PDF(FPDF):
    def header(self):
        # We'll handle custom headers per page type
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by SyncGuard PMS', 0, 0, 'C')

def generate_invoice_pdf(booking_data, property_settings, invoice_num, filepath):
    pdf = PMS_PDF()
    pdf.add_page()
    
    # --- Header Segment ---
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_text_color(30, 41, 59) # Slate 800
    pdf.cell(0, 12, property_settings.get('name', 'Hotel Satsangi').upper(), ln=True)
    
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 116, 139) # Slate 500
    address = property_settings.get('address', 'Near Main Chowk, Valley Road, Manali')
    pdf.multi_cell(0, 4, address)
    pdf.cell(0, 5, f"GSTIN: {property_settings.get('gstNumber', '22AAAAA0000A1Z5')}", ln=True)
    pdf.ln(10)
    
    # --- Invoice Title ---
    pdf.set_fill_color(79, 70, 229) # Indigo 600
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 12, ' TAX INVOICE ', ln=True, fill=True, align='L')
    pdf.ln(5)
    
    # --- Bill To & Info ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(100, 7, 'BILL TO:', 0, 0)
    pdf.cell(0, 7, 'INVOICE DETAILS:', 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    guest_name = booking_data.get('guestName', 'Guest')
    pdf.cell(100, 6, guest_name, 0, 0)
    pdf.cell(40, 6, 'Invoice #:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, str(invoice_num), 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    guest_details = booking_data.get('guestDetails', {})
    if isinstance(guest_details, dict):
        guest_addr = f"{guest_details.get('address', '')}, {guest_details.get('city', '')}"
        pdf.cell(100, 6, guest_addr[:50], 0, 0)
    else:
        pdf.cell(100, 6, 'Address Not Provided', 0, 0)
    
    pdf.cell(40, 6, 'Date:', 0, 0)
    from datetime import datetime
    pdf.cell(0, 6, datetime.now().strftime('%d %b %Y'), 0, 1)
    
    pdf.cell(100, 6, f"Ph: {booking_data.get('phoneNumber', 'N/A')}", 0, 0)
    pdf.cell(40, 6, 'Room:', 0, 0)
    pdf.cell(0, 6, f"#{booking_data.get('roomNumber', 'N/A')}", 0, 1)
    
    pdf.ln(10)
    
    # --- Table Header ---
    pdf.set_fill_color(248, 250, 252) # Slate 50
    pdf.set_text_color(71, 85, 105) # Slate 600
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(100, 10, ' DESCRIPTION', 1, 0, 'L', True)
    pdf.cell(20, 10, 'QTY', 1, 0, 'C', True)
    pdf.cell(30, 10, 'RATE', 1, 0, 'R', True)
    pdf.cell(40, 10, 'AMOUNT ', 1, 1, 'R', True)
    
    # --- Line Items ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    
    total_base = 0
    gst_rate = property_settings.get('gstRate', 12)
    actual_room_tax = 0

    # Stay History consolidation
    stay_history = booking_data.get('stayHistory', [])
    if not stay_history:
        stay_history = [{
            "roomNumber": booking_data.get('roomNumber'),
            "roomTypeName": booking_data.get('roomTypeName'),
            "checkIn": booking_data.get('checkIn'),
            "checkOut": booking_data.get('checkOut'),
            "amount": booking_data.get('amount'),
            "discount": booking_data.get('discount')
        }]

    for segment in stay_history:
        check_in = datetime.strptime(segment['checkIn'], '%Y-%m-%d')
        check_out = datetime.strptime(segment['checkOut'], '%Y-%m-%d')
        nights = max(1, (check_out - check_in).days)
        
        # Rate calculation
        room_rate = segment.get('amount', 0) / nights
        
        # Discount calculation for this segment
        seg_discount = segment.get('discount')
        seg_discount_amount = 0
        if seg_discount:
            if seg_discount.get('type') == 'percentage':
                seg_discount_amount = (room_rate * nights) * (seg_discount.get('value', 0) / 100)
            else:
                seg_discount_amount = seg_discount.get('value', 0)
        
        # Segment Base/Tax
        discounted_seg_total = (room_rate * nights) - seg_discount_amount
        seg_base = discounted_seg_total / (1 + gst_rate / 100)
        seg_tax = discounted_seg_total - seg_base
        
        actual_room_tax += seg_tax
        
        # Display Row
        full_seg_base = (room_rate * nights) / (1 + gst_rate / 100)
        pdf.cell(100, 10, f" Room Rent (#{segment.get('roomNumber')}) - {segment.get('roomTypeName', 'Std')}", 1)
        pdf.cell(20, 10, str(nights), 1, 0, 'C')
        pdf.cell(30, 10, f"{(room_rate / (1 + gst_rate / 100)):,.2f}", 1, 0, 'R')
        pdf.cell(40, 10, f"{full_seg_base:,.2f}", 1, 1, 'R')
        total_base += full_seg_base
        
        if seg_discount_amount > 0:
            pdf.cell(100, 10, f"  > Discount ({seg_discount.get('type','').title()})", 1)
            pdf.cell(20, 10, "-", 1, 0, 'C')
            pdf.cell(30, 10, "", 1, 0, 'R')
            seg_disc_base = seg_discount_amount / (1 + gst_rate / 100)
            pdf.cell(40, 10, f"-{seg_disc_base:,.2f}", 1, 1, 'R')
            total_base -= seg_disc_base

    # Folio items
    total_folio_tax = 0
    for item in booking_data.get('folio', []):
        cat = item.get('category', 'Other')
        cat_upper = (item.get('category', 'Other')).upper()
        desc_upper = (item.get('description', '')).upper()
        f_rate = property_settings.get('otherGstRate', gst_rate) # Default to 12.0 consistency
        if cat_upper == 'F&B': f_rate = property_settings.get('foodGstRate', 5)
        elif cat_upper == 'LAUNDRY': f_rate = property_settings.get('otherGstRate', 18)
        elif any(x in cat_upper for x in ['ROOM', 'ACCOMMODATION']) or 'ROOM RENT' in desc_upper: 
            f_rate = gst_rate
        else: f_rate = property_settings.get('otherGstRate', 12.0)
        
        amount = item.get('amount', 0)
        if item.get('isInclusive'):
            base = amount / (1 + f_rate / 100)
            tax = amount - base
        else:
            base = amount
            tax = amount * (f_rate / 100)

        pdf.cell(100, 10, f" {item['description']} ({cat})", 1)
        pdf.cell(20, 10, '1', 1, 0, 'C')
        pdf.cell(30, 10, f"{base:,.2f}", 1, 0, 'R')
        pdf.cell(40, 10, f"{base:,.2f}", 1, 1, 'R')
        total_base += base
        total_folio_tax += tax
        
    # --- Totals ---
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 10)
    
    grand_total = total_base + actual_room_tax + total_folio_tax
    
    pdf.cell(150, 8, 'SUBTOTAL (Excl. Tax)', 0, 0, 'R')
    pdf.cell(40, 8, f"{total_base:,.2f}", 0, 1, 'R')
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(150, 8, f'GST Portion', 0, 0, 'R')
    pdf.cell(40, 8, f"{(actual_room_tax + total_folio_tax):,.2f}", 0, 1, 'R')
    
    pdf.ln(2)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(150, 12, ' GRAND TOTAL ', 0, 0, 'R', True)
    pdf.cell(40, 12, f"INR {grand_total:,.2f} ", 0, 1, 'R', True)
    
    pdf.ln(20)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.multi_cell(0, 4, "Terms & Conditions:\n1. This is a computer generated invoice.\n2. All disputes are subject to local jurisdiction.\n3. Please quote the invoice number for any future correspondence.")

    pdf.output(filepath)

def generate_receipt_pdf(booking_data, property_settings, invoice_num, filepath):
    pdf = PMS_PDF()
    pdf.add_page()
    
    # --- Header Segment ---
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 12, property_settings.get('name', 'Hotel Satsangi').upper(), ln=True)
    
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, property_settings.get('address', 'Property Address'), ln=True)
    pdf.ln(10)
    
    # --- Receipt Title ---
    pdf.set_fill_color(16, 185, 129) # Emerald 500
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 12, ' OFFICIAL PAYMENT RECEIPT ', ln=True, fill=True, align='L')
    pdf.ln(5)
    
    # --- Info ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 7, 'Referencing Invoice:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, str(invoice_num), 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 7, 'Received From:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, booking_data.get('guestName', 'Guest'), 0, 1)
    
    pdf.ln(10)
    
    # --- Payments Table ---
    pdf.set_fill_color(248, 250, 252)
    pdf.set_text_color(71, 85, 105)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(60, 10, ' DATE', 1, 0, 'L', True)
    pdf.cell(70, 10, ' PAYMENT METHOD', 1, 0, 'L', True)
    pdf.cell(60, 10, ' AMOUNT ', 1, 1, 'R', True)
    
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    
    total_received = 0
    # Standalone Payments
    for p in booking_data.get('payments', []):
        if p.get('status') == 'Completed':
            date_str = p.get('timestamp', '')[:10]
            pdf.cell(60, 10, f" {date_str}", 1)
            pdf.cell(70, 10, f" {p.get('method', 'Unknown')}", 1)
            pdf.cell(60, 10, f"{p.get('amount', 0):,.2f} ", 1, 1, 'R')
            total_received += p.get('amount', 0)
            
    # Paid Folio items (if they were paid separately)
    # Note: If they were settled during checkout, they appear as 'Settled'
    # but we usually only include actual cash/upi/card transactions in a receipt.
    # However, for completeness, we list all paid items.
    
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(130, 12, ' TOTAL AMOUNT RECEIVED ', 0, 0, 'R')
    pdf.set_text_color(16, 185, 129) # Emerald 500
    pdf.cell(60, 12, f"INR {total_received:,.2f} ", 0, 1, 'R')
    
    pdf.ln(30)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 10, 'Authorized Signatory', 0, 1, 'R')
    pdf.set_font('Helvetica', '', 8)
    pdf.cell(0, 5, '(This is a computer generated receipt)', 0, 1, 'R')

    pdf.output(filepath)
