from fpdf import FPDF
import os

class PMS_PDF(FPDF):
    def header(self):
        # We'll handle custom headers per page type
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by SyncGuard PMS', 0, 0, 'C')

def generate_invoice_pdf(booking_data, property_settings, invoice_num, filepath):
    pdf = PMS_PDF()
    pdf.add_page()
    
    # --- Header Segment ---
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_text_color(30, 41, 59) # Slate 800
    pdf.cell(0, 12, property_settings.get('name', 'Hotel Satsangi').upper(), ln=True)
    
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 116, 139) # Slate 500
    address = property_settings.get('address', 'Near Main Chowk, Valley Road, Manali')
    pdf.multi_cell(0, 4, address)
    pdf.cell(0, 5, f"GSTIN: {property_settings.get('gstNumber', '22AAAAA0000A1Z5')}", ln=True)
    pdf.ln(10)
    
    # --- Invoice Title ---
    pdf.set_fill_color(79, 70, 229) # Indigo 600
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 12, ' TAX INVOICE ', ln=True, fill=True, align='L')
    pdf.ln(5)
    
    # --- Bill To & Info ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(100, 7, 'BILL TO:', 0, 0)
    pdf.cell(0, 7, 'INVOICE DETAILS:', 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    guest_name = booking_data.get('guestName', 'Guest')
    pdf.cell(100, 6, guest_name, 0, 0)
    pdf.cell(40, 6, 'Invoice #:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, str(invoice_num), 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    guest_details = booking_data.get('guestDetails', {})
    if isinstance(guest_details, dict):
        guest_addr = f"{guest_details.get('address', '')}, {guest_details.get('city', '')}"
        pdf.cell(100, 6, guest_addr[:50], 0, 0)
    else:
        pdf.cell(100, 6, 'Address Not Provided', 0, 0)
    
    pdf.cell(40, 6, 'Date:', 0, 0)
    from datetime import datetime
    pdf.cell(0, 6, datetime.now().strftime('%d %b %Y'), 0, 1)
    
    pdf.cell(100, 6, f"Ph: {booking_data.get('phoneNumber', 'N/A')}", 0, 0)
    pdf.cell(40, 6, 'Room:', 0, 0)
    pdf.cell(0, 6, f"#{booking_data.get('roomNumber', 'N/A')}", 0, 1)
    
    pdf.ln(10)
    
    # --- Table Header ---
    pdf.set_fill_color(248, 250, 252) # Slate 50
    pdf.set_text_color(71, 85, 105) # Slate 600
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(100, 10, ' DESCRIPTION', 1, 0, 'L', True)
    pdf.cell(20, 10, 'QTY', 1, 0, 'C', True)
    pdf.cell(30, 10, 'RATE', 1, 0, 'R', True)
    pdf.cell(40, 10, 'AMOUNT ', 1, 1, 'R', True)
    
    # --- Line Items ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    
    total_base = 0
    # Room Rent calculation
    check_in = datetime.strptime(booking_data['checkIn'], '%Y-%m-%d')
    check_out = datetime.strptime(booking_data['checkOut'], '%Y-%m-%d')
    nights = max(1, (check_out - check_in).days)
    
    room_rate = 0
    if booking_data.get('source') == 'Direct':
        # Default to the booking amount / nights if no direct base price in property
        room_rate = booking_data.get('amount', 0) / nights
    else:
        room_rate = booking_data.get('amount', 0) / nights
    
    gst_rate = property_settings.get('gstRate', 12)
    
    # Calculate Room Discount first
    discount = booking_data.get('discount')
    room_discount_amount = 0
    if discount:
        if discount.get('type') == 'percentage':
            room_discount_amount = (room_rate * nights) * (discount.get('value', 0) / 100)
        else:
            room_discount_amount = discount.get('value', 0)
    
    # Inclusive Room Calculation
    discounted_room_total = (room_rate * nights) - room_discount_amount
    room_base = discounted_room_total / (1 + gst_rate / 100)
    room_tax = discounted_room_total - room_base
    
    pdf.cell(100, 10, f" Room Rent (#{booking_data.get('roomNumber')}) - {booking_data.get('roomTypeName', 'Standard')}", 1)
    pdf.cell(20, 10, str(nights), 1, 0, 'C')
    # Show base rate (exclusive of GST) in Rate column
    base_rate = room_rate / (1 + gst_rate / 100)
    pdf.cell(30, 10, f"{base_rate:,.2f}", 1, 0, 'R')
    # Show room base (exclusive of GST) in Amount column
    pdf.cell(40, 10, f"{room_base:,.2f}", 1, 1, 'R')
    total_base += room_base
    
    # If discount applied, show as a separate line (negative) - wait, if room_base is already discounted, 
    # then total_base already reflects it. But we should ideally show the discount line for clarity.
    if room_discount_amount > 0:
        pdf.cell(100, 10, f" Discount ({discount.get('type', '').title()}: {discount.get('value')})", 1)
        pdf.cell(20, 10, "", 1, 0, 'C')
        pdf.cell(30, 10, "", 1, 0, 'R')
        disc_base = room_discount_amount / (1 + gst_rate / 100)
        # Note: We already used room_base which is (rent-disc)/1.12. 
        # So total_base calculation is correct. 
        # For display, if we show full rent then discount, it's clearer.
        # Let's re-calculate to show full rent then discount line.
    
    # Re-doing for clarity:
    pdf.set_y(pdf.get_y() - 10) # Go back
    full_room_base = (room_rate * nights) / (1 + gst_rate / 100)
    pdf.cell(100, 10, f" Room Rent (#{booking_data.get('roomNumber')})", 1)
    pdf.cell(20, 10, str(nights), 1, 0, 'C')
    pdf.cell(30, 10, f"{(room_rate / (1 + gst_rate / 100)):,.2f}", 1, 0, 'R')
    pdf.cell(40, 10, f"{full_room_base:,.2f}", 1, 1, 'R')
    total_base = full_room_base
    
    if room_discount_amount > 0:
        pdf.cell(100, 10, f" Discount ({discount.get('type', '').title()}: {discount.get('value')})", 1)
        pdf.cell(20, 10, "-", 1, 0, 'C')
        pdf.cell(30, 10, "", 1, 0, 'R')
        disc_base = room_discount_amount / (1 + gst_rate / 100)
        pdf.cell(40, 10, f"-{disc_base:,.2f}", 1, 1, 'R')
        total_base -= disc_base

    # Folio items - handle both inclusive and exclusive pricing
    total_folio_tax = 0
    for item in booking_data.get('folio', []):
        cat = item.get('category', 'Other')
        is_inclusive = item.get('isInclusive', False)
        
        f_rate = 18
        if cat == 'F&B': f_rate = property_settings.get('foodGstRate', 5)
        elif cat == 'Laundry': f_rate = property_settings.get('otherGstRate', 18)
        else: f_rate = property_settings.get('otherGstRate', 18)
        
        if is_inclusive:
            # For inclusive items, back out the tax from the amount
            item_base = item['amount'] / (1 + f_rate / 100)
            item_tax = item['amount'] - item_base
        else:
            # For exclusive items, tax is added on top
            item_base = item['amount']
            item_tax = item['amount'] * (f_rate / 100)
        
        pdf.cell(100, 10, f" {item['description']} ({cat})", 1)
        pdf.cell(20, 10, '1', 1, 0, 'C')
        pdf.cell(30, 10, f"{item_base:,.2f}", 1, 0, 'R')
        pdf.cell(40, 10, f"{item_base:,.2f}", 1, 1, 'R')
        total_base += item_base
        total_folio_tax += item_tax
        
    # --- Totals ---
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 10)
    
    # Calculate Total Tax
    room_tax = (total_base - sum(i['amount'] for i in booking_data.get('folio', []))) * (gst_rate / 100)
    # Wait, the room tax is correctly the remainder of the inclusive price
    actual_room_tax = (discounted_room_total) - room_base
    
    grand_total = total_base + actual_room_tax + total_folio_tax
    
    pdf.cell(150, 8, 'SUBTOTAL (Excl. Tax)', 0, 0, 'R')
    pdf.cell(40, 8, f"{total_base:,.2f}", 0, 1, 'R')
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(150, 8, f'GST Portion', 0, 0, 'R')
    pdf.cell(40, 8, f"{(actual_room_tax + total_folio_tax):,.2f}", 0, 1, 'R')
    
    pdf.ln(2)
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(150, 12, ' GRAND TOTAL ', 0, 0, 'R', True)
    pdf.cell(40, 12, f"INR {grand_total:,.2f} ", 0, 1, 'R', True)
    
    pdf.ln(20)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.multi_cell(0, 4, "Terms & Conditions:\n1. This is a computer generated invoice.\n2. All disputes are subject to local jurisdiction.\n3. Please quote the invoice number for any future correspondence.")

    pdf.output(filepath)

def generate_receipt_pdf(booking_data, property_settings, invoice_num, filepath):
    pdf = PMS_PDF()
    pdf.add_page()
    
    # --- Header Segment ---
    pdf.set_font('Helvetica', 'B', 20)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(0, 12, property_settings.get('name', 'Hotel Satsangi').upper(), ln=True)
    
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, property_settings.get('address', 'Property Address'), ln=True)
    pdf.ln(10)
    
    # --- Receipt Title ---
    pdf.set_fill_color(16, 185, 129) # Emerald 500
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 12, ' OFFICIAL PAYMENT RECEIPT ', ln=True, fill=True, align='L')
    pdf.ln(5)
    
    # --- Info ---
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 7, 'Referencing Invoice:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, str(invoice_num), 0, 1)
    
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(40, 7, 'Received From:', 0, 0)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 7, booking_data.get('guestName', 'Guest'), 0, 1)
    
    pdf.ln(10)
    
    # --- Payments Table ---
    pdf.set_fill_color(248, 250, 252)
    pdf.set_text_color(71, 85, 105)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(60, 10, ' DATE', 1, 0, 'L', True)
    pdf.cell(70, 10, ' PAYMENT METHOD', 1, 0, 'L', True)
    pdf.cell(60, 10, ' AMOUNT ', 1, 1, 'R', True)
    
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', '', 10)
    
    total_received = 0
    # Standalone Payments
    for p in booking_data.get('payments', []):
        if p.get('status') == 'Completed':
            date_str = p.get('timestamp', '')[:10]
            pdf.cell(60, 10, f" {date_str}", 1)
            pdf.cell(70, 10, f" {p.get('method', 'Unknown')}", 1)
            pdf.cell(60, 10, f"{p.get('amount', 0):,.2f} ", 1, 1, 'R')
            total_received += p.get('amount', 0)
            
    # Paid Folio items (if they were paid separately)
    # Note: If they were settled during checkout, they appear as 'Settled'
    # but we usually only include actual cash/upi/card transactions in a receipt.
    # However, for completeness, we list all paid items.
    
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(130, 12, ' TOTAL AMOUNT RECEIVED ', 0, 0, 'R')
    pdf.set_text_color(16, 185, 129) # Emerald 500
    pdf.cell(60, 12, f"INR {total_received:,.2f} ", 0, 1, 'R')
    
    pdf.ln(30)
    pdf.set_text_color(30, 41, 59)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 10, 'Authorized Signatory', 0, 1, 'R')
    pdf.set_font('Helvetica', '', 8)
    pdf.cell(0, 5, '(This is a computer generated receipt)', 0, 1, 'R')

    pdf.output(filepath)
