import React, { useState, useMemo } from "react";
import {
  Mail,
  Search,
  CheckCircle2,
  Clock,
  XCircle,
  User,
  Calendar,
  CreditCard,
  ArrowRightCircle,
  Zap,
  Globe,
  Filter,
} from "lucide-react";
import { Booking, RoomType, PropertySettings } from "../types";
import { formatDate } from "../utils";

interface EmailParsingViewProps {
  bookings: Booking[];
  roomTypes: RoomType[];
  propertySettings: PropertySettings | null;
  onSelectBooking?: (booking: Booking) => void;
}

const EmailParsingView: React.FC<EmailParsingViewProps> = ({
  bookings,
  roomTypes,
  propertySettings,
  onSelectBooking,
}) => {
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("all");

  // Get all email-parsed bookings (auto-generated)
  const emailBookings = useMemo(() => {
    return bookings
      .filter((b) => b.isAutoGenerated)
      .sort((a, b) => (b.timestamp || 0) - (a.timestamp || 0));
  }, [bookings]);

  // Apply filters
  const filteredBookings = useMemo(() => {
    let result = emailBookings;
    if (statusFilter !== "all") {
      result = result.filter((b) => b.status === statusFilter);
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase().trim();
      result = result.filter((b) => {
        const fields = [
          b.id,
          b.guestName,
          b.roomNumber,
          b.reservationId,
          b.source,
        ];
        return fields.some((f) => f && f.toLowerCase().includes(q));
      });
    }
    return result;
  }, [emailBookings, statusFilter, searchQuery]);

  // Stats
  const stats = useMemo(() => {
    const total = emailBookings.length;
    const confirmed = emailBookings.filter(
      (b) => b.status === "Confirmed",
    ).length;
    const checkedIn = emailBookings.filter(
      (b) => b.status === "CheckedIn",
    ).length;
    const checkedOut = emailBookings.filter(
      (b) => b.status === "CheckedOut",
    ).length;
    const cancelled = emailBookings.filter(
      (b) => b.status === "Cancelled" || b.status === "Rejected",
    ).length;
    const totalRevenue = emailBookings.reduce(
      (sum, b) => sum + (b.amount || 0),
      0,
    );
    const sources: Record<string, number> = {};
    emailBookings.forEach((b) => {
      sources[b.source] = (sources[b.source] || 0) + 1;
    });
    return {
      total,
      confirmed,
      checkedIn,
      checkedOut,
      cancelled,
      totalRevenue,
      sources,
    };
  }, [emailBookings]);

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "CheckedIn":
        return (
          <span className="text-[9px] font-black uppercase tracking-widest bg-emerald-100 text-emerald-700 px-2.5 py-1 rounded-lg">
            In-House
          </span>
        );
      case "Confirmed":
        return (
          <span className="text-[9px] font-black uppercase tracking-widest bg-blue-100 text-blue-700 px-2.5 py-1 rounded-lg">
            Confirmed
          </span>
        );
      case "CheckedOut":
        return (
          <span className="text-[9px] font-black uppercase tracking-widest bg-slate-100 text-slate-500 px-2.5 py-1 rounded-lg">
            Checked Out
          </span>
        );
      default:
        return (
          <span className="text-[9px] font-black uppercase tracking-widest bg-rose-100 text-rose-600 px-2.5 py-1 rounded-lg">
            {status}
          </span>
        );
    }
  };

  const getSourceColor = (source: string) => {
    switch (source) {
      case "MMT":
        return "bg-orange-100 text-orange-700 border-orange-200";
      case "Booking.com":
        return "bg-blue-100 text-blue-700 border-blue-200";
      case "Expedia":
        return "bg-yellow-100 text-yellow-700 border-yellow-200";
      default:
        return "bg-slate-100 text-slate-600 border-slate-200";
    }
  };

  return (
    <div className="h-full flex flex-col bg-[#f8fafc] overflow-hidden">
      {/* Header */}
      <header className="px-8 py-6 bg-white border-b border-slate-100 shadow-sm shrink-0">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl text-white shadow-lg shadow-indigo-200">
              <Mail className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-2xl font-black text-slate-900 tracking-tight">
                Email Parsing
              </h1>
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">
                AI-Powered Booking Extraction • {stats.total} Total Parsed
              </p>
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          <div className="bg-gradient-to-br from-slate-50 to-slate-100/50 rounded-xl p-4 border border-slate-200/50">
            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">
              Total Parsed
            </p>
            <p className="text-2xl font-black text-slate-900 tabular-nums">
              {stats.total}
            </p>
          </div>
          <div className="bg-gradient-to-br from-blue-50 to-blue-100/50 rounded-xl p-4 border border-blue-200/50">
            <p className="text-[9px] font-black text-blue-500 uppercase tracking-widest mb-1">
              Confirmed
            </p>
            <p className="text-2xl font-black text-blue-700 tabular-nums">
              {stats.confirmed}
            </p>
          </div>
          <div className="bg-gradient-to-br from-emerald-50 to-emerald-100/50 rounded-xl p-4 border border-emerald-200/50">
            <p className="text-[9px] font-black text-emerald-500 uppercase tracking-widest mb-1">
              In-House
            </p>
            <p className="text-2xl font-black text-emerald-700 tabular-nums">
              {stats.checkedIn}
            </p>
          </div>
          <div className="bg-gradient-to-br from-slate-50 to-slate-100/50 rounded-xl p-4 border border-slate-200/50">
            <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">
              Checked Out
            </p>
            <p className="text-2xl font-black text-slate-600 tabular-nums">
              {stats.checkedOut}
            </p>
          </div>
          <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl p-4 border border-indigo-200/50">
            <p className="text-[9px] font-black text-indigo-500 uppercase tracking-widest mb-1">
              Revenue
            </p>
            <p className="text-2xl font-black text-indigo-700 tabular-nums">
              ₹{stats.totalRevenue.toLocaleString()}
            </p>
          </div>
        </div>

        {/* Source breakdown */}
        {Object.keys(stats.sources).length > 0 && (
          <div className="flex items-center gap-3 mt-4">
            <Globe className="w-3.5 h-3.5 text-slate-400" />
            <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">
              Sources:
            </span>
            {Object.entries(stats.sources).map(([source, count]) => (
              <span
                key={source}
                className={`text-[9px] font-black uppercase tracking-widest px-2.5 py-1 rounded-lg border ${getSourceColor(source)}`}
              >
                {source}: {count}
              </span>
            ))}
          </div>
        )}
      </header>

      {/* Toolbar */}
      <div className="px-8 py-4 flex items-center gap-4 bg-white border-b border-slate-100 shrink-0">
        <div className="flex-1 relative">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by name, booking ID, PNR..."
            className="w-full pl-10 pr-4 py-2.5 text-sm font-bold text-slate-900 placeholder:text-slate-400 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-400 transition-all"
          />
        </div>
        <div className="flex items-center gap-1 bg-slate-50 border border-slate-200 rounded-xl p-1">
          <Filter className="w-3.5 h-3.5 text-slate-400 ml-2" />
          {[
            { label: "All", value: "all" },
            { label: "Confirmed", value: "Confirmed" },
            { label: "In-House", value: "CheckedIn" },
            { label: "Departed", value: "CheckedOut" },
          ].map((f) => (
            <button
              key={f.value}
              onClick={() => setStatusFilter(f.value)}
              className={`px-3 py-1.5 text-[10px] font-black uppercase tracking-widest rounded-lg transition-all ${statusFilter === f.value ? "bg-white text-indigo-600 shadow-sm" : "text-slate-400 hover:text-slate-600"}`}
            >
              {f.label}
            </button>
          ))}
        </div>
      </div>

      {/* Booking List */}
      <div className="flex-1 overflow-auto px-8 py-6">
        {filteredBookings.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <div className="w-16 h-16 bg-slate-100 rounded-2xl flex items-center justify-center mb-4">
              <Mail className="w-8 h-8 text-slate-300" />
            </div>
            <p className="text-sm font-black text-slate-400">
              No email-parsed bookings found
            </p>
            <p className="text-[10px] font-bold text-slate-300 mt-1">
              {emailBookings.length === 0
                ? "Forward OTA confirmation emails to start parsing"
                : "Try adjusting your filters"}
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {filteredBookings.map((b) => {
              const rt = roomTypes.find((t) => t.id === b.roomTypeId);
              const parsedTime = b.timestamp ? new Date(b.timestamp) : null;
              const hasPrepayment =
                b.payments &&
                b.payments.some(
                  (p) =>
                    p.method === "Online (OTA)" ||
                    p.description?.includes("Pre-paid"),
                );

              return (
                <div
                  key={b.id}
                  onClick={() => onSelectBooking?.(b)}
                  className="bg-white rounded-2xl border border-slate-200/80 p-5 hover:shadow-lg hover:border-indigo-200 transition-all cursor-pointer group"
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-10 h-10 rounded-xl flex items-center justify-center text-white font-black text-sm ${b.source === "MMT" ? "bg-gradient-to-br from-orange-500 to-red-500" : b.source === "Booking.com" ? "bg-gradient-to-br from-blue-500 to-blue-700" : b.source === "Expedia" ? "bg-gradient-to-br from-yellow-500 to-amber-600" : "bg-gradient-to-br from-slate-500 to-slate-700"}`}
                      >
                        {b.source.substring(0, 2).toUpperCase()}
                      </div>
                      <div>
                        <div className="flex items-center gap-2 mb-0.5">
                          <p className="text-sm font-black text-slate-900 uppercase tracking-tight">
                            {b.guestName}
                          </p>
                          {getStatusBadge(b.status)}
                        </div>
                        <div className="flex items-center gap-2">
                          <span className="text-[10px] font-bold text-slate-400">
                            ID: {b.id}
                          </span>
                          {b.reservationId && (
                            <>
                              <span className="text-slate-300">•</span>
                              <span className="text-[10px] font-bold text-slate-400">
                                PNR: {b.reservationId}
                              </span>
                            </>
                          )}
                        </div>
                      </div>
                    </div>

                    <div className="text-right">
                      <p className="text-lg font-black text-slate-900 tabular-nums">
                        ₹{(b.amount || 0).toLocaleString()}
                      </p>
                      {hasPrepayment && (
                        <span className="text-[9px] font-black uppercase tracking-widest text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-lg">
                          Prepaid
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="flex items-center gap-6 text-[10px] font-bold text-slate-400">
                    <div className="flex items-center gap-1.5">
                      <Calendar className="w-3 h-3" />
                      <span>
                        {formatDate(b.checkIn)} → {formatDate(b.checkOut)}
                      </span>
                    </div>
                    {rt && (
                      <div className="flex items-center gap-1.5">
                        <User className="w-3 h-3" />
                        <span>{rt.name}</span>
                      </div>
                    )}
                    {b.roomNumber && b.roomNumber !== "Unassigned" && (
                      <span className="bg-slate-100 text-slate-600 px-2 py-0.5 rounded font-black">
                        #{b.roomNumber}
                      </span>
                    )}
                    {b.pax && (
                      <span>
                        {b.pax} Guest{b.pax > 1 ? "s" : ""}
                      </span>
                    )}
                    {parsedTime && (
                      <div className="flex items-center gap-1.5 ml-auto">
                        <Zap className="w-3 h-3 text-indigo-400" />
                        <span className="text-indigo-400">
                          Parsed{" "}
                          {parsedTime.toLocaleDateString(undefined, {
                            month: "short",
                            day: "numeric",
                          })}{" "}
                          at{" "}
                          {parsedTime.toLocaleTimeString([], {
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      </div>
                    )}
                  </div>

                  {/* Click hint */}
                  <div className="flex items-center gap-1 text-[9px] font-black text-indigo-400 uppercase tracking-widest opacity-0 group-hover:opacity-100 transition-all mt-2 pt-2 border-t border-slate-100">
                    View Booking <ArrowRightCircle className="w-3 h-3" />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default EmailParsingView;
